spring.application.name=Inventory-Manager
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:inventorydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

jwt.secret=change-this-to-a-long-random-secret-string-at-least-32-chars
jwt.expiration-ms=86400000

logging.file.name=logs/inventory-manager.log
logging.file.path=logs